// <auto-generated />
namespace ITMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Usersuserroles11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Usersuserroles11));
        
        string IMigrationMetadata.Id
        {
            get { return "202305160607576_Users-user-roles11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
